# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Diatel' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Diatel
   pod 'Kingfisher', '~> 4.0'
   pod 'SwiftyJSON'
   pod 'Alamofire'
   pod 'DLLocalNotifications'
   pod "McPicker"
   pod 'XLPagerTabStrip', '~> 8.0'

end
